### ISSUE TITLE
Test infrastructure using IAM Policy Simulator

### ISSUE THREAD

**Issue by blever** [ambiata/saws#8]
The saws + tarski tests are currently slow, fragile and we don't have very even coverage. Attempt to use the policy simulator http://docs.aws.amazon.com/IAM/latest/UsingPolicySimulatorGuide/iam-policy-simulator-guide.html to build up a cleaner test framework where it is easy to add and verify new policies.

**Comment by markhibberd** [comment]
Closing, cleaning up old not interesting things.
